### PR TITLE
Add better support for Django testing

### PR DESCRIPTION
**Pull request by JsseL**

### CODE REVIEW

**Review by suutari-ai — CHANGES_REQUESTED** [review]
settings should be in a separate file

tests should be runnable with just `pytest` without any arguments.

**Review by frwickst — APPROVED** [review]
image

**Comment by JsseL** [comment]
🙈 So no comments. Ok then, let's :shipit: 

And just in case somebody thought the same thing as I did, we could move the settings into a separate file... perhaps in the next PR 🤔 

And just in case somebody thought you need to pass parameters to the `runtests`, you don't.

**Comment by suutari-ai** [comment]
:hankey:

**Pull request merged**
